{% if not WITH_CPLEX is defined %}
  {% set WITH_CPLEX = 0 %}
{% endif %}

{% if not WITH_GUROBI is defined %}
  {% set WITH_GUROBI = 0 %}
{% endif %}

package:
  {% if WITH_CPLEX == "1" %}
    name: nifty-with-cplex
  {% elif WITH_GUROBI == "1" %}
    name: nifty-with-gurobi
  {% else %}
    name: nifty
  {% endif %}

  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}


  # If we're using a non-tagged revision, append '.postN' to the version
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}

    version: {{tagged_version}}

source:
  path: ../
  patches:
    # See https://github.com/ukoethe/vigra/issues/386
    - patches/vigra-std-threading-detection.patch

build:
  number: 0
  string: py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}_stacked_rag

  script_env:
     - WITH_CPLEX
     - CPLEX_ROOT_DIR
     - WITH_GUROBI
     - GUROBI_ROOT_DIR
     - GUROBI_LIB_WIN # [win]

requirements:
  build:
    - boost 1.63.0
    - python {{PY_VER}}*
    - hdf5 1.10.1 # Need this version to be compatible with current vigra package
    - fastfilters
    {% if WITH_CPLEX is defined and WITH_CPLEX == "1" %}
    - cplex-shared # [not win]
    {% endif %}

    # Must provide symlinks so that the conda doesn't complain when it 'fixes' linking in _nifty.so
    {% if WITH_GUROBI is defined and WITH_GUROBI == "1" %}
    - gurobi-symlink # [not win]
    {% endif %}

  run:
    - boost 1.63.0
    - python {{PY_VER}}*
    - hdf5  1.10.1 # Need this version to be compatible with current vigra package
    - numpy # Numpy version is not constrained, thanks to pybind11 magic
    - fastfilters
    - scikit-image
    - scipy
    - futures # [py2k]

    {% if WITH_CPLEX is defined and WITH_CPLEX == "1" %}
    - cplex-shared # [not win]
    {% endif %}

    {% if WITH_GUROBI is defined and WITH_GUROBI == "1" %}
    - gurobi-symlink # [not win]
    {% endif %}

test:
  {% if WITH_CPLEX is defined and WITH_CPLEX == "1" %}
    imports:
      - nifty_with_cplex
  {% elif WITH_GUROBI is defined and WITH_GUROBI == "1" %}
    imports:
      - nifty_with_gurobi
  {% else %}
    imports:
      - nifty
  {% endif %}

about:
  home: https://github.com/DerThorsten/nifty
  license: MIT
  summary: Graph-based segmentation algorithms
